spring:
                                  datasource:
                                    url: jdbc:mysql://localhost:3306/futbolmanager?serverTimezone=UTC
                                    username: root
                                  jpa:
                                    hibernate:
                                      ddl-auto: create